CRITICAL - 2020-06-12 00:27:16 --> Unknown column 'user.branch_id' in 'on clause'
#0 C:\xampp\htdocs\test_backend\system\Database\MySQLi\Connection.php(330): mysqli->query('SELECT\r\n       ...')
#1 C:\xampp\htdocs\test_backend\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT\r\n       ...')
#2 C:\xampp\htdocs\test_backend\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\r\n       ...')
#3 C:\xampp\htdocs\test_backend\app\Models\User_Model.php(247): CodeIgniter\Database\BaseConnection->query('SELECT\r\n       ...')
#4 C:\xampp\htdocs\test_backend\app\Controllers\User.php(70): App\Models\User_Model->get_branchsystem('35', '1')
#5 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(910): App\Controllers\User->authenticate()
#6 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test_backend\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-06-12 02:38:24 --> Column 'branch_id' in group statement is ambiguous
#0 C:\xampp\htdocs\test_backend\system\Database\MySQLi\Connection.php(330): mysqli->query('SELECT\r\n\t\t\t\t\t`b...')
#1 C:\xampp\htdocs\test_backend\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT\r\n\t\t\t\t\t`b...')
#2 C:\xampp\htdocs\test_backend\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT\r\n\t\t\t\t\t`b...')
#3 C:\xampp\htdocs\test_backend\app\Models\Maindata_Model.php(54): CodeIgniter\Database\BaseConnection->query('SELECT\r\n\t\t\t\t\t`b...')
#4 C:\xampp\htdocs\test_backend\app\Controllers\Dashboard.php(48): App\Models\Maindata_Model->get_branch('44')
#5 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(910): App\Controllers\Dashboard->index()
#6 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#7 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\test_backend\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-06-12 06:07:36 --> ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Head...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\test_backend\system\Session\Handlers\FileHandler.php(101): ini_set('session.save_pa...', 'C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\test_backend\system\Config\Services.php(765): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\App), '172.68.6.37')
#3 C:\xampp\htdocs\test_backend\system\Config\BaseService.php(123): CodeIgniter\Config\Services::session(Object(Config\App), false)
#4 C:\xampp\htdocs\test_backend\system\Config\Services.php(754): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#5 C:\xampp\htdocs\test_backend\app\Controllers\Manga\Manga.php(24): CodeIgniter\Config\Services::session()
#6 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(882): App\Controllers\Manga\Manga->__construct()
#7 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(393): CodeIgniter\CodeIgniter->createController()
#8 C:\xampp\htdocs\test_backend\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test_backend\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2020-06-12 06:07:36 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\test_backend\app\Config\Events.php:27) in C:\xampp\htdocs\test_backend\system\Debug\Exceptions.php:161
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 161, Array)
#1 C:\xampp\htdocs\test_backend\system\Debug\Exceptions.php(161): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
